### PR TITLE
Added PeekMessage

### PR DESCRIPTION
**Pull request by TheNoim**

### CODE REVIEW

**Comment by dunklesToast** [comment]
Looks good. Also need this! Please merge!

**Comment by waitingsong** [comment]
```
C:/projects/myproject/src/lib/user32/api.ts:42:1
ERROR: 42:1  max-line-length  Exceeds maximum line length of 120
```
please fix

**Comment by waitingsong** [comment]
@TheNoim 
why do you change pkg.name and url of the package.json ?
https://github.com/waitingsong/node-win32-api/pull/4/commits/1305ddf292454cee0bc3124fead1ffce2f428498

**Comment by TheNoim** [comment]
@waitingsong Sorry worked on a project and needed a quick version with this method which just works. This is why I republished it under win32-api-fork. Still hope this can be merge into this repo. Of course not with the changes I made to the package.json. 
A line length for this type of project does not make sense. If you add more win32 definitions later, of course will the file be longer than 120 lines. I suggest removing any line limitations.

**Pull request merged**
